import 'package:flutter/material.dart';

const UNIVERSITIES_DROP_DOWN_MENU_ENTRIES = [
  DropdownMenuEntry(value: 'narxoz', label: 'Narxoz University'),
  DropdownMenuEntry(value: 'sdu', label: 'SDU University'),
  DropdownMenuEntry(value: 'kbtu', label: 'KBTU'),
  DropdownMenuEntry(value: "kaznu", label: "Al-Farabi KazNU"),
  DropdownMenuEntry(value: 'satbayev', label: 'Satbayev University'),
  DropdownMenuEntry(value: 'iitu', label: 'IITU'),
  DropdownMenuEntry(
    value: 'eurasian',
    label: 'Gumilyov Eurasian National University',
  ),
  DropdownMenuEntry(
    value: 'karaganda',
    label: 'Karaganda Technical University',
  ),
  DropdownMenuEntry(value: 'aktobe', label: 'Aktobe Regional University'),
  DropdownMenuEntry(
    value: 'east_kazakhstan',
    label: 'East Kazakhstan University',
  ),
  DropdownMenuEntry(
    value: 'asfendiyarov',
    label: 'Asfendiyarov Kazakh National Medical University',
  ),
  DropdownMenuEntry(value: 'kostanay', label: 'Kostanay Regional University'),
];

const EVENTS_DROP_DOWN_MENU_ENTRIES = [
  DropdownMenuEntry(value: 'hackathon', label: 'Hackathon'),
  DropdownMenuEntry(value: 'mvp', label: 'MVP Project'),
  DropdownMenuEntry(value: 'final', label: 'FINAL project'),
  DropdownMenuEntry(value: "game jam", label: "Game Jam"),
  DropdownMenuEntry(value: "startup", label: "Startup"),
];

// Event types for filtering in feed
const EVENT_TYPES = [
  {'title': 'hackathon', 'emoji': '🏆'},
  {'title': 'mvp', 'emoji': '🏆'},
  {'title': 'practice', 'emoji': '📚'},
  {'title': 'final', 'emoji': '🏆'},
  {'title': 'startup', 'emoji': '🚀'},
  {'title': 'game jam', 'emoji': '🚀'},
];

const COURSES_DROP_DOWN_MENU_ENTRIES = [
  DropdownMenuEntry(value: "1", label: "1 course"),
  DropdownMenuEntry(value: "2", label: "2 course"),
  DropdownMenuEntry(value: "3", label: "3 course"),
  DropdownMenuEntry(value: "4", label: "4 course"),
];

const AVAILABLE_SKILLS = [
  'React',
  'Python',
  'UI/UX',
  'TypeScript',
  'Figma',
  'Data Science',
  'Node.js',
  'Flutter',
  'Vue.js',
  'Angular',
  'Django',
  'FastAPI',
  'PostgreSQL',
  'MongoDB',
  'Firebase',
  'Docker',
  'Kubernetes',
  'AWS',
  'GCP',
  'Azure',
  'GraphQL',
  'REST API',
  'Microservices',
  'DevOps',
  'CI/CD',
  'Git',
  'Linux',
  'Bash',
  'Java',
  'C++',
  'C#',
  'Ruby',
  'PHP',
  'Go',
  'Rust',
  'Swift',
  'Kotlin',
  'Android',
  'iOS',
  'Web Design',
  'Mobile Design',
  'Prototype',
  'UX Research',
  'Product Management',
  'Agile',
  'Scrum',
  'Leadership',
  'Communication',
  'Problem Solving',
  'Machine Learning',
  'Deep Learning',
  'NLP',
  'Computer Vision',
  'TensorFlow',
  'PyTorch',
  'Pandas',
  'NumPy',
  'Matplotlib',
  'Excel',
  'SQL',
  'NoSQL',
  'Redis',
  'Elasticsearch',
  'RabbitMQ',
  'Kafka',
  'Blockchain',
  'Web3',
  'Smart Contracts',
  'Solidity',
];
