// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADn8y9qZAWgz8JoRUV7gz9q8iOpgURgQk',
    appId: '1:441848863591:web:9de47f8f59e51d9ea1edc2',
    messagingSenderId: '441848863591',
    projectId: 'pm-project-1ec4d',
    authDomain: 'pm-project-1ec4d.firebaseapp.com',
    storageBucket: 'pm-project-1ec4d.firebasestorage.app',
    measurementId: 'G-XMBXRQW4WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBivS34lP9F7BlWVIDWt2SIQHbyIwZfnPQ',
    appId: '1:441848863591:android:828ec745b3c2ea9ca1edc2',
    messagingSenderId: '441848863591',
    projectId: 'pm-project-1ec4d',
    storageBucket: 'pm-project-1ec4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArvV45CLe4w_umZZwMD23BsBZhOXD4sCY',
    appId: '1:441848863591:ios:9dbe28412470d923a1edc2',
    messagingSenderId: '441848863591',
    projectId: 'pm-project-1ec4d',
    storageBucket: 'pm-project-1ec4d.firebasestorage.app',
    iosBundleId: 'com.example.teamup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArvV45CLe4w_umZZwMD23BsBZhOXD4sCY',
    appId: '1:441848863591:ios:9dbe28412470d923a1edc2',
    messagingSenderId: '441848863591',
    projectId: 'pm-project-1ec4d',
    storageBucket: 'pm-project-1ec4d.firebasestorage.app',
    iosBundleId: 'com.example.teamup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADn8y9qZAWgz8JoRUV7gz9q8iOpgURgQk',
    appId: '1:441848863591:web:d37abdf03c63f201a1edc2',
    messagingSenderId: '441848863591',
    projectId: 'pm-project-1ec4d',
    authDomain: 'pm-project-1ec4d.firebaseapp.com',
    storageBucket: 'pm-project-1ec4d.firebasestorage.app',
    measurementId: 'G-4PRQXPBJW2',
  );
}
